### ISSUE TITLE
Moving to npm

### ISSUE THREAD

**Issue by ToniKorin** [morungos/cordova-plugin-ios-safari#2]
Thanks for this plugin. Any plans to move the plugin into npm?
Some instruction can be found from there:
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by morungos** [comment]
Oh I hadn't known about that. But thanks for alerting me to it. I'll get on it.

**Comment by morungos** [comment]
Now published at: https://www.npmjs.com/package/cordova-plugin-ios-safari. Updated to version 0.1.2 for this.
